apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compliance-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods        # Pods are used to run the compliance container
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - watch       # The operator needs to watch for the container status
  - create      # The operator needs to spawn the containers
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps  # The log collecting sidecar uses configmaps to store results
  verbs:
  - create      # The sidecar must create the configmap to store results in
  - get
  - list       # The Suite controller must list configMaps
  - watch      # The Suite controller must watch configMaps
  - patch      # The Suite controller annotates configMaps
  - update     # The Suite controller annotates configMaps
- apiGroups:
  - ""
  resources:
  - secrets  # Secrets are used to store TLS assets
  verbs:
  - create   # The operator must create certificate secrets
  - get
  - list
  - update
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get         # Otherwise the operator errors out when creating initializing metrics
  - list        # The resultserver needs to be created and tracked
  - watch
  - create
  - update
  - delete      # The compliance-scan controller deletes the resultserver in the DONE phase
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancescans   # The operator's custom CRD
  verbs:
  - create      # The Suite ctrl must be able to create Scans
  - watch       # The operator must be able to watch the CR for changes
  - patch       # The operator changes the CR status to run a state machine
  - get         # The operator must be able to read the CR
  - list        # The operator must be able to read the CR
- apiGroups:
  - compliance.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - compliance-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services    # Services is the way we provide metrics for the operator
  - services/finalizers
  verbs:
  - create      # The operator needs to create a service to expose the metrics and resultserver
  - get
  - update
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - compliance-operator
  verbs:
  - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-operator
rules:
- apiGroups:
  - ""
  resources:
  - nodes  # We need to list the nodes to be able to selectively scan
  verbs:
  - list
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs  # The compliance remediation controller operates on MachineConfigs
  - machineconfigpools
  verbs:
  - list
  - get
  - patch
  - create
  - watch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resultscollector
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancescans
  verbs:
  - get
- apiGroups:
  - security.openshift.io
  resourceNames:
  - node-exporter
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediation-aggregator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - update
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancescans
  verbs:
  - get
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancescans/finalizers
  - compliancechecks/finalizers
  verbs:
  - update
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations
  verbs:
  - create
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancechecks
  verbs:
  - create
  - get
