apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compliance-operator-chart.fullname" . }}
spec:
  # FIXME(lbragstad): Make the replica count configurable based on a default
  # value in values.yaml
  replicas: 1
  selector:
    matchLabels:
      name: compliance-operator
  template:
    metadata:
      labels:
        name: compliance-operator
      annotations:
        workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      serviceAccountName: compliance-operator
      containers:
        - name: compliance-operator
          image: "quay.io/compliance-operator/compliance-operator:latest"
          command:
          - compliance-operator
          - operator
          - --platform
          - {{ .Values.platform }}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          # FIXME(lbragstad): Consider making this configurable via
          # values.yaml.
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_OPENSCAP
              # Hardcoding this temporarily until its propagated to CI
              value: "quay.io/compliance-operator/openscap-ocp:1.3.5"
            - name: RELATED_IMAGE_OPERATOR
              value: "quay.io/compliance-operator/compliance-operator:latest"
            - name: RELATED_IMAGE_PROFILE
              value: "quay.io/compliance-operator/compliance-operator-content:latest"
          volumeMounts:
            - name: serving-cert
              mountPath: /var/run/secrets/serving-cert
              readOnly: true
      volumes:
        - name: serving-cert
          secret:
            secretName: compliance-operator-serving-cert
            optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
